apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-db
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: pokeapi/db
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: pokeapi/db
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: pokeapi/db
        property: POSTGRES_PASSWORD
