apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "pokeapi-db"
          serviceAccountRef:
            name: default
