{{- range $name, $wl := .Values.workloads }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-deployment
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $wl.image }}
          ports:
            - containerPort: {{ $wl.containerPort }}
---
{{- end }}