{{- range $name, $wl := .Values.workloads }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-service
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $wl.servicePort }}
      targetPort: {{ $wl.containerPort }}
  type: ClusterIP
---
{{- end }}