workloads:
  pokemonslider:
    image: jeffhemmen/2048-pokemon
    host: pokemonslider.localhost
    path: /
    containerPort: 80
    servicePort: 80
  tetris:
    image: uzyexe/tetris
    host: tetris.localhost
    path: /
    containerPort: 80
    servicePort: 80

