{{- range $name, $wl := .Values.workloads }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ $.Release.Name }}-{{ $name }}-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: {{ $wl.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $wl.servicePort }}
---
{{- end }}
