{{- range $name, $wl := .Values.workloads }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $wl.host }}
      http:
        paths:
          - path: {{ $wl.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $wl.servicePort }}
---
{{- end }}
