imagePullSecrets:
  - name: regcred

workloads:
  pokeviewer:
    image: fogshaper/experimentingspace:pokemon-viewer
    path: /pokedex
    containerPort: 3000
    servicePort: 3000
    env:
      POKEAPI_BASE_URL: http://pokeapi-pokeapi.pokeapi.svc.cluster.local
