apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openbao.github.io/openbao-helm
    chart: openbao
    targetRevision: 0.29.2
    helm:
      values: |
        server:
          dev:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
