apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokeapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/voidworm/mylittleplayground.git
    targetRevision: main
    path: pokeapi
  destination:
    server: https://kubernetes.default.svc
    namespace: pokeapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
